# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 13:57:24 2024

@author: aidan
"""

# Project 4

import numpy as np
from numpy.linalg import eig
import cmath

def spectral_radius(A):
    '''
    Author : Aidan Hembruff
    
    A function which finds the eigenvalue with the maximum
    absolute value for a 2-D array

    Parameters
    ----------
    A : The input 2-dimensional matrix

    Returns
    -------
    The eigenvalue of the matrix with the maximum absolute value

    '''
    eigenvalues = eig(A)[0] # eigenvalues of A
    return np.max(np.abs(eigenvalues)) # maximum absolute eigenvalue

def make_tridiagonal(N,b,d,a):
    '''
    A function which takes numerical inputs to generate an NxN
    tridiagnonal matrix with specified values

    Parameters
    ----------
    N : The length of the array's rows and columns
    
    b : The value which will go on the lower diagonal
    
    d : The value which will go on the main diagonal
    
    a : The value which will go on the upper diagonal

    Returns
    -------
    The tridiagonal matrix generated by the input values

    '''
    # create the tridiagonal matrix by summing matrices with the specified values,
    # on the lower, main, and upper diagonals
    return d*np.identity(N)+(b*np.eye(N,k=-1))+(a*np.eye(N,k=1)) 

def make_initialcond(xi,k0,sigma0):
    '''
    Author : Aidan Hembruff
    
    A function which returns the initial wavepacket of a given form
    based on scalable input parameters and grid
    
    Parameters
    ----------
    xi : The spatial grid which the wavepacket will be a function of
    
    k0 : Scalable parameter for the wavepacket
    
    sigma0 : Scalable parameter for the wavepacket

    Returns
    -------
    The wavepacket function determined by the parameters and spatial grid

    '''
    return (np.exp((-(xi**2))/(2*(sigma0**2))))*np.cos(k0*xi) # wavepacket function

def sch_eqn(nspace,ntime,tau,method="ftcs",lenght=200,potential=[],wparam=[10,0,0.5]):
    
    hbar = 1
    ftcs_coeff = 1j*tau/hbar 
    
    crank_coeff = 1j*tau/(2*hbar)
    
    H = make_tridiagonal(nspace,1,-2,1)
    return

def sch_plot(plot_type="psi",save=True):
    
    return